cadastro/cad_clientes/urls.py
from django.urls import path
from cadastro.cad_clientes.views import novo, detail, ListaClientes, Alteracao, Exclusao

app_name = 'cad_clientes'

urlpatterns = [
    path('', novo, name='novo'),
    path('ListaClientes', ListaClientes, name='ListaClientes'),
    path('<int:pk>/', detail, name='detail'),
    path('Alteracao/<int:pk>/', Alteracao, name='Alteracao'),
    path('Exclusao/<int:pk>/', Exclusao, name='Exclusao'),
]

cadastro/urls.py
from django.contrib import admin
from django.urls import path, include
from cadastro.core.views import home
from cadastro.cad_clientes.views import novo

urlpatterns = [
    path('', home, name='home'),
    path('cliente/', include('cadastro.cad_clientes.urls')),
    path('admin/', admin.site.urls),
]

cadastro/cad_clientes/models.py
from django.db import models

list_UF = [('', ''),('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), 
           ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), 
           ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ',), ('RN', 'RN'), ('RS', 'RS'), 
           ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')]

# Create your models here.
class CadCliente(models.Model):
    razaoSocial     = models.CharField('Razão Social', max_length=150)   
    nomeFantasia    = models.CharField('Nome Fantasia', max_length=100)
    cep             = models.CharField('CEP', max_length=8)
    endereco        = models.CharField('Endereço', max_length=200)
    numero          = models.CharField('Numero', max_length=10)
    uf              = models.CharField('UF', max_length=2, choices=list_UF)
    cnpj            = models.CharField('CNPJ', max_length=11)
    consumidorFinal = models.BooleanField('Consumidor Final', default=False)
    criado          = models.DateTimeField('Criado em', auto_now_add=True)

cadastro/cad_clientes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from cadastro.cad_clientes.models import CadCliente

# Personalisar mensagem de erro para todos os campos
REQUIRED = dict(required=('Campo Obrigatório'))

class CadClienteFormOld(forms.Form):
    cnpj            = forms.CharField(label='CNPJ:')
    razaoSocial     = forms.CharField(label='Razão Social:')   
    nomeFantasia    = forms.CharField(label='Nome Fantasia:')
    cep             = forms.CharField(label='CEP:')
    endereco        = forms.CharField(label='Endereço:', required=True)
    numero          = forms.CharField(label='Numero:')
    uf              = forms.ChoiceField(label='UF:')
    consumidorFinal = forms.BooleanField(label='Consumidor Final', required=False)
    # 

class CadClienteForm(forms.ModelForm):
   # uf = forms.ChoiceField(choices=list_UF,label='UF:')
    class Meta:
        model = CadCliente
        fields = ['cnpj', 'razaoSocial', 'nomeFantasia', 'cep', 'endereco', 'numero', 'uf', 'consumidorFinal']
        error_messages = {f.name: REQUIRED for f in  CadCliente._meta.fields} # Personalisar mensagem de erro para todos os campos

cadastro/cad_clientes/views.py
from django.shortcuts import render, resolve_url as r, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from cadastro.cad_clientes.forms import CadClienteForm
from cadastro.cad_clientes.models import CadCliente

# Create your views here.
def novo(request):
    if request.method == 'POST':
        return inclusao(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'cad_clientes/cad_clientes_form.html',
                    {'form': CadClienteForm()})


def inclusao(request):
    form = CadClienteForm(request.POST)

    if not form.is_valid():
        return render(request, 'cad_clientes/cad_clientes_form.html',
                        {'form': form})

    cadcliente = form.save()

    return HttpResponseRedirect(r('cad_clientes:detail', cadcliente.pk))

def detail(request, pk):
    try:
        cadcliente = CadCliente.objects.get(pk=pk)  

    except CadCliente.DoesNotExist:
        pass

    return render(request, 'cad_clientes/cad_clientes_detail.html',
                  {'cad_cliente': cadcliente})
   

def ListaClientes(request):

    lista_clientes = CadCliente.objects.all()

    return render(request, 'cad_clientes/lista_clientes.html',
                  {'lista_clientes': lista_clientes})

def Alteracao(request, pk):
    cliente = CadCliente.objects.get(pk=pk)
    
    if request.method == 'POST':
        form = CadClienteForm(request.POST, instance=cliente)

        if not form.is_valid():
            return render(request, 'cad_clientes/cad_clientes_form.html',
                {'form': form})

        form.save()
        return HttpResponseRedirect(r('cad_clientes:ListaClientes'))
    else:
        form = CadClienteForm(instance=cliente)   
        return render(request, 'cad_clientes/cad_clientes_form.html', {'form': form})

def Exclusao(request, pk):
    cliente = CadCliente.objects.get(pk=pk)
    
    if request.method == 'POST':
        cliente.delete()
        return HttpResponseRedirect(r('cad_clientes:ListaClientes'))


    # form = CadClienteForm(instance=cliente)   
    return render(request, 'cad_clientes/cad_cliente_confirma_exclusao.html', {'cliente': cliente})    



             

cadastro/core/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'index.html')

cadastro/cad_clientes/templates/cad_clientes/alteracao.html
<p>{{ cliente.pk }}</p>
<p>{{ cliente.cnpj }}</p>
<p>{{ cliente.razaoSocial }}</p>

cadastro/cad_clientes/templates/cad_clientes/cad_cliente_confirma_exclusao.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Cadastro de Clientes {% endblock title %}

{% block content %}

<div class="position-sticky text-center">
    <h2>Atenção! Cliente será excluido!</h2>   
</div>   

<div class="container">
    <h2></h2>
    <div>
        <form action="." method="POST">
            {% csrf_token %}
            <p>{{ cliente.pk }}</p>
            <p>{{ cliente.cnpj }}</p>
            <p>{{ cliente.razaoSocial }}</p>
        
            <button type="submit" class="btn btn-primary"  >Confirmar Exclusão</button>

        </form>


    </div>

</div>    


{% endblock content %}

cadastro/cad_clientes/templates/cad_clientes/cad_clientes_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Cliente Cadastrado {% endblock title %}

{% block content %}

<h1>Cliente Cadastrado</h1>

<p>Codigo: {{ cad_cliente.pk }}</p>
<p>CNPJ: {{ cad_cliente.cnpj }}</p>
<p>Razão Social: {{ cad_cliente.razaoSocial }} </p>


{% endblock content %}

cadastro/cad_clientes/templates/cad_clientes/cad_clientes_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Cadastro de Clientes {% endblock title %}

{% block content %}

<div class="container">

  <form action="." novalidate method="POST">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-3">
        <label for="{{ form.cnpj.id_for_label }}">{{ form.cnpj.label }}</label>
        {% render_field form.cnpj.errors %}  
        {% render_field form.cnpj class="form-control" %}                
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ form.razaoSocial.id_for_label }}">{{ form.razaoSocial.label }}</label>
        {{ form.razaoSocial.errors }}
        {% render_field form.razaoSocial|attr:'required:true' class="form-control" %}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ form.nomeFantasia.id_for_label }}">{{ form.nomeFantasia.label }}</label>
        {{ form.nomeFantasia.errors }}
        {% render_field form.nomeFantasia class="form-control" %}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-2">
        <label for="{{ form.cep.id_for_label }}">{{ form.cep.label }}</label>
        {{ form.cep.errors }}
        {% render_field form.cep class="form-control" placeholder="00000-000" %}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ form.endereco.id_for_label }}">{{ form.endereco.label }}</label>
        {{ form.endereco.errors }}
        {% render_field form.endereco class="form-control" %}
      </div>
      <div class="form-group col-md-2">
        <label for="{{ form.numero.id_for_label }}">{{ form.numero.label }}</label>
        {{ form.numero.errors }}
        {% render_field form.numero class="form-control" %}
      </div>
      <div class="form-group col-md-2">
        <label for="{{ form.uf.id_for_label }}">{{ form.uf.label }}</label>
        {{ form.uf.errors }}
        {% render_field form.uf class="form-control" %}
      </div>
    </div>
    <div class="form-group">
      <div class="form-check">
        {{ form.consumidorFinal.errors }}
        {% render_field form.consumidorFinal class="form-check-input" %}
        <label class="form-check-label"
          for="{{ form.consumidorFinal.id_for_label }}">{{ form.consumidorFinal.label }}</label>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</div>

{% endblock content %}

cadastro/cad_clientes/templates/cad_clientes/lista_clientes.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block title %} Lista de Clientes {% endblock title %}

{% block content %}
   
<div class="position-sticky text-center">
    <h2>Listagem de Clientes</h2>   
</div>   

<div class="container">
    
    <table data-toggle="table" data-search="true" data-show-columns="false">
        <thead>
            <tr>
                <th>ID</th>
                <th>CNPJ</th>
                <th>Razão Social</th>
                <th>Alterar / Deletar</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in lista_clientes  %}
            <tr id="tr-id-1" class="tr-class-1" data-title="bootstrap table" data-object='{"key": "value"}'>
                <td>{{ cliente.pk }}</td>
                <td>{{ cliente.cnpj }}</td>
                <td>{{ cliente.razaoSocial }}</td>
                <td>
                    <a href="{% url 'cad_clientes:Alteracao' pk=cliente.pk %}">Alterar</a>
                    /
                    <a href="{% url 'cad_clientes:Exclusao' pk=cliente.pk %}">Deletar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="container">
    <a href="{% url 'cad_clientes:novo' %}" class="btn btn-dark BtnListClient" role="button" aria-pressed="true">Novo</a>
</div>

{% endblock content %}

cadastro/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

  <title>{% block title %}  {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse container" id="conteudoNavbarSuportado">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(página atual)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cadastro
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'cad_clientes:ListaClientes' %}">Clientes</a>
            </div>          
          </li>
        </ul>
      </div>
    </nav>
    
    {% block content %}
    {% endblock content %}

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
  </body>
</html>

cadastro/core/templates/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}


{% endblock content %}